### PR TITLE
Update for Cosimulation (Parameter Overrides + Misc. Cleanup)

### PR DESCRIPTION
**Pull request by abejgonzalez**
**Related Issues/PRs**: https://github.com/riscv-boom/riscv-boom/pull/415 https://github.com/abejgonzalez/dromajo/pull/1

**Release Notes**:
This PR is all the changes that BOOM (boom-core.org) has done in order to cosimulate using Dromajo. Here is a high-level list of all the changes:

- Add `.gitignore`
- Cleanup `*_cosim.*` functions to be more consistent with other functions within the files
- Added bootrom override
- Added dtb override
- Added parameter to have bootrom and dtb be contiguous
- Added reset vector override
- Added MMIO range override
- Added PLIC base/size overrides
- Added CLINT base/size overrides
- Added parameter to add `X` extension to the `misa` (though it is not used (this aligns with Rocket-Chip))

Any recommendations/concerns are welcome!

### CODE REVIEW

**Comment by et-tommythorn** [comment]
That looks great.  Let me comb it over tomorrow before merging.  Thanks for the improvement.

**Comment by et-tommythorn** [comment]
Ok, I resolved conflicts, squashed, and pushed.

Next time, please make sure that it's rebased on the current master before submitting a request.  Also, do squash all changes unless there a very good reason for individual commits.  Finally, no merge commits, thanks.

**Comment by abejgonzalez** [comment]
Sorry about that, bad habit. Also, I didn't know what the strategy was for doing PRs (rebase or merge commit) so I left that alone for now. In any case, thanks for the review/feedback!

**Comment by et-tommythorn** [comment]
No problem; I was merely providing the requested feedback.  The rebase vs. merges is largely an question of taste (good taste and bad taste :)

**Pull request closed without merging**
